name: Build and deploy NucitaBot

on:
  push:
    branches:
      - main

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    environment: NucitaBotDeploy
    steps:
      - name: deploy bot
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.NUCITA_KEY }}
          command: |
            cd NucitaBot
            git pull 
            npm install
            npm run build
            pm2 restart NucitaBot
