name: Build and deploy NucitaBot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy bot
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.NUCITA_KEY }}
      port: ${{ secrets.PORT }}
      script: |
        cd NucitaBot
        git pull 
        npm install
        npm run build
        pm2 restart NucitaBot
